version: '3'

services:
  web:
    image: nginx:latest
    container_name: cautela_html
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  api:
    build:
      context: ./api/
    container_name: cautela_api
    ports:
      - "3000:3000"
    volumes:
      - ./api/src/db/:/usr/src/app/src/db/
    restart: always
