services:
  web:
    image: nginx:latest
    container_name: gerador_cautela
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
